package AdminGUI;

import assignment.Admin;
import assignment.FileIO;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class AdminEditProfile extends javax.swing.JFrame {

    Admin admin;

    public AdminEditProfile(Admin AD) {
        initComponents();
        this.admin = AD;
        this.UserIDInput.setText(this.admin.getUserIdNum());
        this.NameInput.setText(this.admin.getUserName());
        this.PasswordInput.setText(this.admin.getUserPassword());
        this.AddressInput.setText(this.admin.getUserAddress());
        this.EmailInput.setText(this.admin.getUserEmail());
        String active = "Active";
        this.admin.setUserStatus(active);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        UserIconLabel = new javax.swing.JLabel();
        AdminLabel = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        ManageUserButton = new javax.swing.JButton();
        EditProfileButton = new javax.swing.JButton();
        SystemRecordsButton = new javax.swing.JButton();
        BackToHomeButton = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        EditProfileLabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        UserIDInput = new javax.swing.JTextField();
        PasswordLabel = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        NameLabel = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        AddressLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        ResetButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        AddressInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 32, 63));
        SidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        UserIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconFile/AccountIconBig.png"))); // NOI18N

        AdminLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        AdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminLabel.setText("ADMIN");

        HomeButton.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(0, 32, 63));
        HomeButton.setText("HOME");
        HomeButton.setBorder(new javax.swing.border.MatteBorder(null));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ManageUserButton.setBackground(new java.awt.Color(255, 255, 255));
        ManageUserButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ManageUserButton.setForeground(new java.awt.Color(0, 32, 63));
        ManageUserButton.setText("MANAGE");
        ManageUserButton.setBorder(new javax.swing.border.MatteBorder(null));
        ManageUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageUserButtonActionPerformed(evt);
            }
        });

        EditProfileButton.setBackground(new java.awt.Color(255, 255, 255));
        EditProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EditProfileButton.setForeground(new java.awt.Color(0, 32, 63));
        EditProfileButton.setText("EDIT PROFILE");
        EditProfileButton.setBorder(new javax.swing.border.MatteBorder(null));
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });

        SystemRecordsButton.setBackground(new java.awt.Color(255, 255, 255));
        SystemRecordsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemRecordsButton.setForeground(new java.awt.Color(0, 32, 63));
        SystemRecordsButton.setText("SYSTEM RECORDS");
        SystemRecordsButton.setBorder(new javax.swing.border.MatteBorder(null));
        SystemRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemRecordsButtonActionPerformed(evt);
            }
        });

        BackToHomeButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BackToHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        BackToHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconFile/logout.png"))); // NOI18N
        BackToHomeButton.setText("Back to Home");
        BackToHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackToHomeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SidePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EditProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ManageUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SystemRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(UserIconLabel))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackToHomeButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(UserIconLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AdminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ManageUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SystemRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(BackToHomeButton)
                .addContainerGap())
        );

        getContentPane().add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        EditProfileLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        EditProfileLabel.setForeground(new java.awt.Color(0, 32, 63));
        EditProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EditProfileLabel.setText("EDIT PROFILE");

        UserIDLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UserIDLabel.setText("USER ID:");

        UserIDInput.setEditable(false);
        UserIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDInputActionPerformed(evt);
            }
        });

        PasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordLabel.setText("PASSWORD:");

        NameLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        NameLabel.setText("NAME:");

        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        AddressLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddressLabel.setText("ADDRESS:");

        EmailLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EmailLabel.setText("EMAIL:");

        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });

        ResetButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        UpdateButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        AddressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(EditProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addComponent(ResetButton)
                        .addGap(38, 38, 38)
                        .addComponent(UpdateButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(UserIDLabel)
                                .addGap(33, 33, 33))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NameLabel)
                                    .addComponent(PasswordLabel)
                                    .addComponent(AddressLabel))
                                .addGap(33, 33, 33))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(EmailLabel)
                                .addGap(29, 29, 29)))
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PasswordInput)
                            .addComponent(NameInput)
                            .addComponent(UserIDInput)
                            .addComponent(EmailInput)
                            .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(EditProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIDLabel))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordLabel)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressLabel)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResetButton)
                    .addComponent(UpdateButton))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 760, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        try {
            new AdminHome(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminEditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ManageUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageUserButtonActionPerformed
        new AdminManage(admin).setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageUserButtonActionPerformed

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed

    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void SystemRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemRecordsButtonActionPerformed
        try {
            new AdminSystemInfo(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminEditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_SystemRecordsButtonActionPerformed

    private void BackToHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackToHomeButtonMouseClicked
        try {
            new AdminHome(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminEditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_BackToHomeButtonMouseClicked

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        this.UserIDInput.setText(this.admin.getUserIdNum());
        this.NameInput.setText(this.admin.getUserName());
        this.PasswordInput.setText(this.admin.getUserPassword());
        this.AddressInput.setText(this.admin.getUserAddress());
        this.EmailInput.setText(this.admin.getUserEmail());
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        String newAddress = this.AddressInput.getText().trim();
        String newEmail = this.EmailInput.getText().trim();
        String newName = this.NameInput.getText().trim();
        String newPassword = this.PasswordInput.getText().trim();

        if (!newPassword.isEmpty() && !newPassword.equals(this.admin.getUserPassword())) {
            this.admin.setUserPassword(newPassword);
        }
        if (!newName.isEmpty() && !newName.equals(this.admin.getUserName())) {
            this.admin.setUserName(newName);
        }
        if (!newEmail.isEmpty() && !newEmail.equals(this.admin.getUserEmail())) {
            this.admin.setUserEmail(newEmail);
        }
        if (!newAddress.isEmpty() && !newAddress.equals(this.admin.getUserAddress())) {
            this.admin.setUserAddress(newAddress);
        }
        String[] newDetails = {this.admin.getUserIdNum(), newPassword, newName, newAddress, newEmail, this.admin.getStatus()};
        File file = FileIO.searchFilePath("Admin.txt");
        String filePath = file.getAbsolutePath();
        try {
            if (FileIO.modifyFile(filePath, this.admin.getUserIdNum(), newDetails, 6)) {
                JOptionPane.showMessageDialog(null, "Profile successfully updated!");
            } else {
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminEditProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void UserIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDInputActionPerformed

    }//GEN-LAST:event_UserIDInputActionPerformed

    private void AddressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditProfile(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressInput;
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JLabel BackToHomeButton;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JLabel EditProfileLabel;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton ManageUserButton;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JButton ResetButton;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton SystemRecordsButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UserIDInput;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JLabel UserIconLabel;
    // End of variables declaration//GEN-END:variables
}
