package AdminGUI;

import LoginGUI.LoginInterface;
import assignment.Admin;
import assignment.FileIO;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

public class AdminHome extends javax.swing.JFrame {

    Admin admin;

    public AdminHome(Admin Admin) throws IOException {
        initComponents();
        this.admin = Admin;
        JTable PMTable = this.ProductManagerTable;
        JTable SPTable = this.SupplierTable;
        JTable PCTable = this.ProductCategoryTable;
        JTable PITable = this.ProductItemTable;
        FileIO fileIO = new FileIO();
        File ProductManagerFile = fileIO.searchFilePath("ProductManager.txt");
        File SupplierFile = fileIO.searchFilePath("Supplier.txt");
        File ProductItemFile = fileIO.searchFilePath("ProductItem.txt");
        File ProductCategoryFile = fileIO.searchFilePath("ProductCategory.txt");
        String[] PMcolumnsName = {"ID", "Pass", "Name", "Address", "Email", "Status"};
        String[] SPcolumnsName = {"ID", "Pass", "Name", "Address", "Email", "Status"};
        String[] PIcolumnsName = {"ID", "Brand", "Name", "CategoryID", "Quantity", "Retail Price", "Description", "ImagePath", "SupplierID"};
        String[] PCcolumnsName = {"ID", "Name", "Description"};
        fileIO.buildTable(ProductManagerFile, PMTable, PMcolumnsName);
        fileIO.buildTable(SupplierFile, SPTable, SPcolumnsName);
        fileIO.buildTable(ProductItemFile, PITable, PIcolumnsName);
        fileIO.buildTable(ProductCategoryFile, PCTable, PCcolumnsName);
        TableColumn tcolPM = PMTable.getColumnModel().getColumn(1);
        TableColumn tcolSP = SPTable.getColumnModel().getColumn(1);
        PMTable.removeColumn(tcolPM);
        SPTable.removeColumn(tcolSP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserIconLabel = new javax.swing.JLabel();
        DashboardAdminLabel = new javax.swing.JLabel();
        ManageProductButton = new javax.swing.JButton();
        ManageProfileButton = new javax.swing.JButton();
        SystemRecordsButton = new javax.swing.JButton();
        EditProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductItemTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ProductManagerTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        ProductCategoryTable = new javax.swing.JTable();
        SupplierLabel = new javax.swing.JLabel();
        ProductManagerLabel = new javax.swing.JLabel();
        ProductCategoryLabel = new javax.swing.JLabel();
        ProductItemLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));

        UserIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconFile/AccountIcon.png"))); // NOI18N

        DashboardAdminLabel.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        DashboardAdminLabel.setForeground(new java.awt.Color(255, 255, 255));
        DashboardAdminLabel.setText("DASHBOARD ADMIN");

        ManageProductButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ManageProductButton.setText("MANAGE PRODUCT/CATEGORY");
        ManageProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProductButtonActionPerformed(evt);
            }
        });

        ManageProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ManageProfileButton.setText("MANAGE PROFILE");
        ManageProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageProfileButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageProfileButtonMouseEntered(evt);
            }
        });
        ManageProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageProfileButtonActionPerformed(evt);
            }
        });

        SystemRecordsButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SystemRecordsButton.setText("SYSTEM RECORDS");
        SystemRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemRecordsButtonActionPerformed(evt);
            }
        });

        EditProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        EditProfileButton.setText("EDIT PROFILE");
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });

        LogoutButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconFile/logout.png"))); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });

        ProductItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ProductItemTable);

        ProductManagerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(ProductManagerTable);

        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(SupplierTable);

        ProductCategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(ProductCategoryTable);

        SupplierLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SupplierLabel.setForeground(new java.awt.Color(255, 255, 255));
        SupplierLabel.setText("SUPPLIER");

        ProductManagerLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProductManagerLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProductManagerLabel.setText("PRODUCT MANAGER");

        ProductCategoryLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProductCategoryLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProductCategoryLabel.setText("PRODUCT CATEGORY");

        ProductItemLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ProductItemLabel.setForeground(new java.awt.Color(255, 255, 255));
        ProductItemLabel.setText("PRODUCT ITEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(ProductManagerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SupplierLabel)
                .addGap(220, 220, 220))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(UserIconLabel)
                .addGap(204, 204, 204)
                .addComponent(DashboardAdminLabel)
                .addContainerGap(285, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(ProductCategoryLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProductItemLabel)
                .addGap(208, 208, 208))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EditProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageProfileButton)
                .addGap(8, 8, 8)
                .addComponent(ManageProductButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SystemRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DashboardAdminLabel)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(UserIconLabel)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SupplierLabel)
                    .addComponent(ProductManagerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProductCategoryLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProductItemLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SystemRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManageProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ManageProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProductButtonActionPerformed
        new AdminManageProduct(admin).setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageProductButtonActionPerformed

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        new AdminEditProfile(admin).setVisible(true);
        dispose();
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void ManageProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageProfileButtonActionPerformed
        new AdminManageUser(admin).setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageProfileButtonActionPerformed

    private void SystemRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemRecordsButtonActionPerformed
        try {
            new AdminSystemInfo(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_SystemRecordsButtonActionPerformed

    private void ManageProfileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProfileButtonMouseEntered

    }//GEN-LAST:event_ManageProfileButtonMouseEntered

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        FileIO read = new FileIO();
        try {
            read.writeLoginRecords("Admin", admin.getUserIdNum(), "Logout", "Success");
        } catch (IOException ex) {
            Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        new LoginInterface().setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void ManageProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageProfileButtonMouseClicked

    }//GEN-LAST:event_ManageProfileButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminHome(null).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(AdminHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashboardAdminLabel;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JButton ManageProductButton;
    private javax.swing.JButton ManageProfileButton;
    private javax.swing.JLabel ProductCategoryLabel;
    private javax.swing.JTable ProductCategoryTable;
    private javax.swing.JLabel ProductItemLabel;
    private javax.swing.JTable ProductItemTable;
    private javax.swing.JLabel ProductManagerLabel;
    private javax.swing.JTable ProductManagerTable;
    private javax.swing.JLabel SupplierLabel;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JButton SystemRecordsButton;
    private javax.swing.JLabel UserIconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
