package AdminGUI;

import assignment.Admin;
import assignment.FileIO;
import assignment.Supplier;
import assignment.productManager;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jared
 */
public class RegisterUser extends javax.swing.JFrame {
    Admin admin;
    FileIO file = new FileIO();
    productManager pm = new productManager(null);
    Supplier sp = new Supplier(null);
    public RegisterUser(Admin AD) {
        initComponents();
        this.admin = AD;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BacktoHomeButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        ManageButton = new javax.swing.JButton();
        EditProfileButton = new javax.swing.JButton();
        SystemRecordsButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        UserPositionComboBox = new javax.swing.JComboBox<>();
        RegisterUserLabel = new javax.swing.JLabel();
        UserIDInput = new javax.swing.JTextField();
        UserTypeLabel = new javax.swing.JLabel();
        UserIDLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        GenerateButton = new javax.swing.JButton();
        AddressInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 32, 63));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BacktoHomeButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BacktoHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        BacktoHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconFile/logout.png"))); // NOI18N
        BacktoHomeButton.setText("Back to Home");
        BacktoHomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BacktoHomeButtonMouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconFile/AccountIconBig.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ADMIN");

        HomeButton.setBackground(new java.awt.Color(255, 255, 255));
        HomeButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        HomeButton.setForeground(new java.awt.Color(0, 32, 63));
        HomeButton.setText("HOME");
        HomeButton.setBorder(new javax.swing.border.MatteBorder(null));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        ManageButton.setBackground(new java.awt.Color(255, 255, 255));
        ManageButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ManageButton.setForeground(new java.awt.Color(0, 32, 63));
        ManageButton.setText("MANAGE");
        ManageButton.setBorder(new javax.swing.border.MatteBorder(null));
        ManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageButtonActionPerformed(evt);
            }
        });

        EditProfileButton.setBackground(new java.awt.Color(255, 255, 255));
        EditProfileButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        EditProfileButton.setForeground(new java.awt.Color(0, 32, 63));
        EditProfileButton.setText("EDIT PROFILE");
        EditProfileButton.setBorder(new javax.swing.border.MatteBorder(null));
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });

        SystemRecordsButton.setBackground(new java.awt.Color(255, 255, 255));
        SystemRecordsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemRecordsButton.setForeground(new java.awt.Color(0, 32, 63));
        SystemRecordsButton.setText("SYSTEM RECORDS");
        SystemRecordsButton.setBorder(new javax.swing.border.MatteBorder(null));
        SystemRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemRecordsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ManageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SystemRecordsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BacktoHomeButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ManageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SystemRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(BacktoHomeButton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        UserPositionComboBox.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UserPositionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Product Manager", "Supplier", " " }));
        UserPositionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPositionComboBoxActionPerformed(evt);
            }
        });

        RegisterUserLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        RegisterUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegisterUserLabel.setText("REGISTER USER");

        UserIDInput.setEditable(false);
        UserIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDInputActionPerformed(evt);
            }
        });

        UserTypeLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UserTypeLabel.setText("USER TYPE:");

        UserIDLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        UserIDLabel.setText("USER ID:");

        PasswordLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        PasswordLabel.setText("PASSWORD:");

        PasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordInputActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("NAME:");

        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("ADDRESS:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("EMAIL:");

        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        GenerateButton.setText("Generate");
        GenerateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(RegisterUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(156, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubmitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PasswordLabel)
                                    .addComponent(UserIDLabel)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(UserTypeLabel))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(PasswordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                    .addComponent(NameInput)
                                    .addComponent(EmailInput)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(UserPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(UserIDInput))
                                        .addGap(18, 18, 18)
                                        .addComponent(GenerateButton))
                                    .addComponent(AddressInput))))))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(RegisterUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserPositionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UserIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UserIDLabel))
                    .addComponent(GenerateButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 760, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserPositionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPositionComboBoxActionPerformed
        this.UserIDInput.setText(null);
    }//GEN-LAST:event_UserPositionComboBoxActionPerformed

    private void BacktoHomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BacktoHomeButtonMouseClicked
        try {
            new AdminHome(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_BacktoHomeButtonMouseClicked

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailInputActionPerformed

    private void UserIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDInputActionPerformed
        
        
    }//GEN-LAST:event_UserIDInputActionPerformed
   
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        File filePath = null;
        if ("".equals(this.UserIDInput.getText())||"".equals(this.PasswordInput.getText())||"".equals(this.NameInput.getText())||"".equals(this.AddressInput.getText())||"".equals(this.EmailInput.getText())){
            JOptionPane.showMessageDialog(null,"Please insert all the data!");
        }
        else{
        String Position = (String) UserPositionComboBox.getSelectedItem();
        if ("Admin".equals(Position)){
            
            filePath = file.searchFilePath(admin.getFileName());
            
        }
        else if ("Product Manager".equals(Position)){
            filePath = file.searchFilePath(pm.getFileName());
        }
        else if ("Supplier".equals(Position)){
            filePath = file.searchFilePath(sp.getFileName());
        }
        
        String userID = UserIDInput.getText();  
        String userPass = PasswordInput.getText();String userName= NameInput.getText();String userAdd= AddressInput.getText(); String userEmail= EmailInput.getText();String userStatus= "Active";
        String [] details ={userID,userPass,userName,userAdd,userEmail,userStatus};
        file.writeDetails(filePath, details,6);
        }
        JOptionPane.showMessageDialog(null,"Successfully registered new user!");
        this.UserIDInput.setText(null);this.PasswordInput.setText(null);this.NameInput.setText(null);this.AddressInput.setText(null);this.EmailInput.setText(null);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        try {
            new AdminHome(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageButtonActionPerformed
        new AdminManage(admin).setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageButtonActionPerformed

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        new AdminEditProfile(admin).setVisible(true);
        dispose();
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void SystemRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemRecordsButtonActionPerformed
        try {
            new AdminSystemInfo(admin).setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_SystemRecordsButtonActionPerformed

    private void PasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordInputActionPerformed

    private void GenerateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateButtonActionPerformed
        File filePath;String generatedID;
        String Position = (String) UserPositionComboBox.getSelectedItem();
        if (Position == "Admin"){
            admin.setFileName("Admin.txt");
            filePath = file.searchFilePath(admin.getFileName());
            try {
                generatedID = admin.generateUserID(filePath);
                this.UserIDInput.setText(generatedID);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if (Position == "Product Manager"){
            
            pm.setFileName("ProductManager.txt");
            filePath = file.searchFilePath(pm.getFileName());
            try {
                generatedID = pm.generateUserID(filePath);
                this.UserIDInput.setText(generatedID);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
        else if (Position == "Supplier"){
            sp.setFileName("Supplier.txt");
            filePath = file.searchFilePath(sp.getFileName());
            try {
                generatedID = sp.generateUserID(filePath);
                this.UserIDInput.setText(generatedID);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_GenerateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterUser(null).setVisible(true);
                
            }
        }
        );
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressInput;
    private javax.swing.JLabel BacktoHomeButton;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JButton GenerateButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton ManageButton;
    private javax.swing.JTextField NameInput;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel RegisterUserLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton SystemRecordsButton;
    private javax.swing.JTextField UserIDInput;
    private javax.swing.JLabel UserIDLabel;
    private javax.swing.JComboBox<String> UserPositionComboBox;
    private javax.swing.JLabel UserTypeLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
